---
- include: packages-apt.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: packages-yum.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
